northwind:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: hsc26372.us-east-1

      # Authentication using environment variables
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: accountadmin
      database: northwind
      warehouse: xsmall_wh
      schema: raw
      threads: 12
      client_session_keep_alive: False